"""Initial schema: jobs, applications, admins.

Revision ID: 0001
Revises:
Create Date: 2026-01-01

Hand-written and reviewed rather than blindly autogenerated, because the partial
unique index at the bottom (the duplicate-application rule) is something
autogenerate renders awkwardly.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

EMPLOYMENT_TYPES = ("FULL_TIME", "PART_TIME", "CONTRACT", "INTERNSHIP")
APPLICATION_STATUSES = ("APPLIED", "SCREENING", "INTERVIEW", "SELECTED", "REJECTED")


def upgrade() -> None:
    # ---------------------------------------------------------------- jobs --
    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_code", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("department", sa.String(length=100), nullable=False),
        sa.Column("location", sa.String(length=100), nullable=False),
        # VARCHAR + CHECK rather than a native PostgreSQL ENUM: adding a value
        # later needs no ALTER TYPE, and the same DDL works on SQLite in tests.
        sa.Column(
            "employment_type",
            sa.Enum(*EMPLOYMENT_TYPES, name="employmenttype", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("responsibilities", sa.Text(), nullable=False),
        sa.Column("skills", sa.Text(), nullable=False),
        sa.Column("experience_required", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_jobs_job_code", "jobs", ["job_code"], unique=True)
    op.create_index("ix_jobs_department", "jobs", ["department"])
    op.create_index("ix_jobs_location", "jobs", ["location"])
    op.create_index("ix_jobs_employment_type", "jobs", ["employment_type"])
    op.create_index("ix_jobs_is_active", "jobs", ["is_active"])
    # Serves the careers page's exact query: active jobs, newest first.
    op.create_index("ix_jobs_active_created", "jobs", ["is_active", "created_at"])

    # -------------------------------------------------------------- admins --
    op.create_table(
        "admins",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        # bcrypt hash only. There is no plaintext password column anywhere.
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=150), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_admins_email", "admins", ["email"], unique=True)

    # -------------------------------------------------------- applications --
    op.create_table(
        "applications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("application_code", sa.String(length=32), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=30), nullable=False),
        sa.Column("experience", sa.String(length=100), nullable=False),
        sa.Column("profile_url", sa.String(length=500), nullable=True),
        # S3 object key only — never the resume bytes (RESTRICTIONS.md #23).
        sa.Column("resume_key", sa.String(length=500), nullable=True),
        sa.Column("cover_note", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(*APPLICATION_STATUSES, name="applicationstatus", native_enum=False, length=20),
            server_default="APPLIED",
            nullable=False,
        ),
        sa.Column("admin_notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name="fk_applications_job_id", ondelete="CASCADE"
        ),
    )
    op.create_index("ix_applications_application_code", "applications", ["application_code"], unique=True)
    op.create_index("ix_applications_job_id", "applications", ["job_id"])
    op.create_index("ix_applications_email", "applications", ["email"])
    op.create_index("ix_applications_status", "applications", ["status"])
    op.create_index("ix_applications_created_at", "applications", ["created_at"])
    op.create_index("ix_applications_job_status", "applications", ["job_id", "status"])

    # The duplicate-application business rule, enforced by the database as a
    # backstop against two concurrent submissions slipping past the service
    # check: one LIVE application per (job, email). Rejected candidates may
    # re-apply, so those rows are excluded.
    op.create_index(
        "uq_applications_job_email_active",
        "applications",
        ["job_id", "email"],
        unique=True,
        postgresql_where=sa.text("status <> 'REJECTED'"),
        sqlite_where=sa.text("status <> 'REJECTED'"),
    )


def downgrade() -> None:
    op.drop_table("applications")
    op.drop_table("admins")
    op.drop_table("jobs")
