import { useEffect, useState, type FormEvent } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { jobsApi } from '@/api/jobs';
import { ApiError, toApiError } from '@/api/client';
import { Button } from '@/components/common/Button';
import { ErrorMessage } from '@/components/common/ErrorMessage';
import { SelectField, TextAreaField, TextField } from '@/components/common/FormField';
import { LoadingSpinner } from '@/components/common/LoadingSpinner';
import { useDocumentTitle } from '@/hooks/useDocumentTitle';
import { EMPLOYMENT_TYPE_LABELS, EmploymentType, type JobPayload } from '@/types/api';

const DEPARTMENTS = [
  'Engineering', 'Human Resources', 'Finance', 'Sales',
  'Marketing', 'Operations', 'Support', 'Design', 'Data',
];
const LOCATIONS = ['Delhi NCR', 'Bengaluru', 'Mumbai', 'Hyderabad', 'Pune', 'Remote'];

const EMPTY: JobPayload = {
  title: '',
  department: 'Engineering',
  location: 'Bengaluru',
  employment_type: EmploymentType.FULL_TIME,
  description: '',
  responsibilities: '',
  skills: '',
  experience_required: '',
  is_active: true,
};

export default function AdminJobFormPage() {
  const { jobId } = useParams();
  const isEdit = jobId !== undefined && jobId !== 'new';
  const navigate = useNavigate();

  useDocumentTitle(isEdit ? 'Edit job' : 'Create job');

  const [values, setValues] = useState<JobPayload>(EMPTY);
  const [loading, setLoading] = useState(isEdit);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<ApiError | null>(null);
  const [jobCode, setJobCode] = useState<string | null>(null);

  useEffect(() => {
    if (!isEdit) return;
    let cancelled = false;
    jobsApi
      .adminDetail(Number(jobId))
      .then((job) => {
        if (cancelled) return;
        setJobCode(job.job_code);
        setValues({
          title: job.title,
          department: job.department,
          location: job.location,
          employment_type: job.employment_type,
          description: job.description,
          responsibilities: job.responsibilities,
          skills: job.skills,
          experience_required: job.experience_required,
          is_active: job.is_active,
        });
      })
      .catch((caught) => !cancelled && setError(toApiError(caught)))
      .finally(() => !cancelled && setLoading(false));
    return () => {
      cancelled = true;
    };
  }, [isEdit, jobId]);

  const set = <K extends keyof JobPayload>(key: K, value: JobPayload[K]) =>
    setValues((previous) => ({ ...previous, [key]: value }));

  const handleSubmit = async (event: FormEvent) => {
    event.preventDefault();
    setError(null);
    setSaving(true);
    try {
      if (isEdit) await jobsApi.update(Number(jobId), values);
      else await jobsApi.create(values);
      navigate('/admin/jobs');
    } catch (caught) {
      setError(toApiError(caught));
    } finally {
      setSaving(false);
    }
  };

  if (loading) return <LoadingSpinner label="Loading job…" />;

  const fieldError = (name: string) => error?.fields?.[name];

  return (
    <div className="mx-auto max-w-3xl space-y-6">
      <nav aria-label="Breadcrumb" className="text-sm text-slate-500">
        <Link to="/admin/jobs" className="hover:text-brand-700 hover:underline">
          Jobs
        </Link>
        <span className="mx-2" aria-hidden="true">
          /
        </span>
        <span className="text-slate-700">{isEdit ? 'Edit job' : 'Create job'}</span>
      </nav>

      <header>
        <h1 className="text-2xl font-bold tracking-tight text-slate-900">
          {isEdit ? 'Edit job' : 'Create a job'}
        </h1>
        <p className="mt-1 text-sm text-slate-600">
          {isEdit ? (
            <>
              Job code <span className="font-mono">{jobCode}</span>. The code is generated by the
              system and cannot be changed.
            </>
          ) : (
            'The job code is generated automatically when the role is created.'
          )}
        </p>
      </header>

      <form onSubmit={handleSubmit} noValidate className="card space-y-5 p-6 sm:p-8">
        {error && <ErrorMessage error={error} title="Could not save the job" />}

        <TextField
          label="Job title"
          required
          placeholder="Senior FastAPI Developer"
          value={values.title}
          error={fieldError('title')}
          onChange={(event) => set('title', event.target.value)}
        />

        <div className="grid gap-5 sm:grid-cols-3">
          <SelectField
            label="Department"
            required
            value={values.department}
            options={DEPARTMENTS.map((item) => ({ value: item, label: item }))}
            error={fieldError('department')}
            onChange={(event) => set('department', event.target.value)}
          />
          <SelectField
            label="Location"
            required
            value={values.location}
            options={LOCATIONS.map((item) => ({ value: item, label: item }))}
            error={fieldError('location')}
            onChange={(event) => set('location', event.target.value)}
          />
          <SelectField
            label="Employment type"
            required
            value={values.employment_type}
            options={Object.values(EmploymentType).map((type) => ({
              value: type,
              label: EMPLOYMENT_TYPE_LABELS[type],
            }))}
            error={fieldError('employment_type')}
            onChange={(event) => set('employment_type', event.target.value as EmploymentType)}
          />
        </div>

        <TextField
          label="Experience required"
          required
          placeholder="5+ years"
          value={values.experience_required}
          error={fieldError('experience_required')}
          onChange={(event) => set('experience_required', event.target.value)}
        />

        <TextAreaField
          label="Description"
          required
          rows={5}
          placeholder="What the role is and why it exists."
          hint="At least 20 characters."
          value={values.description}
          error={fieldError('description')}
          onChange={(event) => set('description', event.target.value)}
        />

        <TextAreaField
          label="Responsibilities"
          required
          rows={5}
          placeholder={'One per line:\nDesign and build FastAPI services.\nReview pull requests.'}
          hint="Put each responsibility on its own line — the careers page renders them as a list."
          value={values.responsibilities}
          error={fieldError('responsibilities')}
          onChange={(event) => set('responsibilities', event.target.value)}
        />

        <TextAreaField
          label="Skills"
          required
          rows={3}
          placeholder="Python, FastAPI, PostgreSQL, Docker"
          hint="Comma separated — these become the skill tags on the job page."
          value={values.skills}
          error={fieldError('skills')}
          onChange={(event) => set('skills', event.target.value)}
        />

        <label className="flex items-start gap-3 rounded-lg bg-slate-50 p-4">
          <input
            type="checkbox"
            className="mt-0.5 h-4 w-4 rounded border-slate-300 text-brand-600 focus:ring-brand-500"
            checked={values.is_active ?? true}
            onChange={(event) => set('is_active', event.target.checked)}
          />
          <span className="text-sm">
            <span className="font-medium text-slate-900">Publish this role</span>
            <span className="mt-0.5 block text-slate-600">
              Active roles appear on the public careers page and accept applications.
            </span>
          </span>
        </label>

        <div className="flex justify-end gap-3 border-t border-slate-100 pt-5">
          <Button type="button" variant="secondary" onClick={() => navigate('/admin/jobs')}>
            Cancel
          </Button>
          <Button type="submit" loading={saving}>
            {isEdit ? 'Save changes' : 'Create job'}
          </Button>
        </div>
      </form>
    </div>
  );
}
